In [41]:
from VenusOpt.simulator import Venus
from VenusOpt.utils import get_scalar, loadXy
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.model_selection import cross_validate
from sklearn.utils import shuffle
import numpy as np


In [58]:
X, y, X_var = loadXy("../New Data/accumulated_weekend_data.h5", run_idx='3')
X.shape, y.shape, X_var.shape
y = y
gpr = GaussianProcessRegressor(
    alpha=X_var.mean(), n_restarts_optimizer=9
)

X, y = shuffle(X, y)
print(cross_validate(gpr, X, y))

gpr.fit(X, y)

{'fit_time': array([0.03228903, 0.02712154, 0.03459144, 0.03037953, 0.03152633]), 'score_time': array([0.00710821, 0.00655913, 0.0104425 , 0.00610614, 0.00620604]), 'test_score': array([0.59595259, 0.48995663, 0.4979475 , 0.64084297, 0.53412301])}


GaussianProcessRegressor(alpha=0.0009060408920488076, n_restarts_optimizer=9)

In [64]:
y

array([ 1.21848403e-04,  1.36059782e-04,  1.85752787e-04,  1.96470908e-04,
        1.52348200e-04,  9.41895631e-05,  2.01447856e-04,  2.30108313e-04,
        2.07881808e-04,  1.74573218e-04,  1.33712887e-04,  1.73066026e-04,
        2.51530315e-04,  2.34069679e-04,  2.58939146e-04,  2.57010797e-04,
        1.27763069e-04,  2.15052682e-04,  1.41424897e-04,  2.14591918e-04,
        1.85871215e-04,  2.32402921e-04,  1.95737913e-04,  9.82670346e-05,
        1.31543041e-04,  2.53634562e-04,  1.35512233e-04,  1.93055708e-04,
        1.13689244e-04,  2.44354900e-04,  2.01299441e-04,  2.53244344e-04,
        1.21860477e-04,  1.63190995e-04,  1.97420938e-04,  1.58081436e-04,
        2.34940162e-04,  2.49693990e-04,  1.91827046e-04,  1.62391685e-04,
        2.41598700e-04,  1.26694272e-04,  2.15836221e-04,  2.21219723e-04,
        2.15511867e-04,  1.26471864e-04,  2.40810372e-04,  1.55055431e-04,
        2.25638985e-04,  1.45114541e-04,  2.40565626e-04,  2.54738062e-04,
        1.91846064e-04,  

In [59]:
x_scalar = get_scalar()
x_scalar

array([0.07692308, 0.07692308, 0.06666667])

In [60]:
gpr.predict(x_scalar * np.array([105,105,120]).reshape(1,-1))

array([-0.00012012])

In [61]:
unnormalized_gpr = lambda arr: gpr.predict((arr * x_scalar).reshape(1,-1)) * 1000000
venus = Venus(jitter=0.15, func=unnormalized_gpr)

In [62]:
venus.set_mag_currents(105,105,120)
venus.get_beam_current()

array([-120.1190576])